name: ArenaCats
version: '1.7'
main: hu.jgj52.arenaCats.ArenaCats
api-version: '1.21'
authors: [ JGJ52 ]
depend:
  - LibCats
  - WorldEdit
softdepend:
  - WorldGuard
commands:
  arena:
    permission: arenacats.command.arena